apiVersion: v1 
kind: Pod
metadata:
  name: myapp-pod
  labels:
    foo: bar
spec:
  containers:
    - name: nginx
      image: nginx
    - name: postgres-container
      image: postgres
      env:
        - name: POSTGRES_PASSWORD
          value: mysecret
