apiVersion: v1 
kind: Pod
metadata:
  name: foo-pod
  labels:
    type: foo
    tier: front-end
spec:
  containers:
    - name: echo
      image: k8s.gcr.io/echoserver:1.4

---

apiVersion: v1 
kind: Pod
metadata:
  name: bar-pod
  labels:
    type: bar
    tier: front-end
spec:
  containers:
    - name: echo
      image: k8s.gcr.io/echoserver:1.4
