apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: my-replicaset
  labels:
    app: myapp
    type: front-end

spec:
  replicas: 3
  selector: 
    matchLabels:
      foo: bar
  template:
    metadata:
      name: myapp-pod
      labels:
        foo: bar
    spec:
      containers:
        - name: nginx
          image: nginx

