apiVersion: apps/v1
kind: Deployment
metadata: 
  name: foo-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      type: foo
  template:
    metadata:
      name: foo-pod
      labels:
        type: foo 
        tier: front-end
    spec:
      containers:
        - name: echo
          image: k8s.gcr.io/echoserver:1.10

---

apiVersion: apps/v1
kind: Deployment
metadata: 
  name: bar-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      type: bar 
  template:
    metadata:
      name: bar-pod
      labels:
        type: bar
        tier: front-end
    spec:
      containers:
        - name: echo
          image: k8s.gcr.io/echoserver:1.10

---


apiVersion: v1
kind: Service
metadata: 
  name: foo-service
spec:
  ports:
    - targetPort: 8080
      port: 80
  selector:
    type: foo
    tier: front-end

---

apiVersion: v1
kind: Service
metadata: 
  name: bar-service
spec:
  ports:
    - targetPort: 8080
      port: 80
  selector:
    type: bar
    tier: front-end
